baseURL = "https://stevenjohnstone.github.io/pub-blog/"
title = "My Awesome Blog"
[pagination]
  pagerSize = 5
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
    disable = false

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
  description = "This is my awesome blog where I write about stuff."
  author = "Your Name"

  # home-info mode
  [params.homeInfoParams]
    Title = "Hi there ðŸ‘‹"
    Content = "Welcome to my blog"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/<YOUR-GITHUB-USERNAME>"

[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 20